version: "3.8"

services:
  db:
    image: postgres:14
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 0756
      POSTGRES_DB: skill_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remix_app
    ports:
      - "3000:3000"
      - "5173:5173"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:0756@db:5432/skill_db
      NODE_ENV: development
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]

volumes:
  postgres_data:
